import Link from "next/link";
import "./globals.css";
import { Navbar } from "./Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="bg-gray-900 h-screen">
          <Navbar />
          <div className="mx-52">{children}</div>
        </div>
      </body>
    </html>
  );
}
